version: '3'

tasks:
  start:
    cmds:
      - docker compose up
  generate:
    cmds:
      - docker compose exec nuxt-app yarn generate
  preview:
    cmds:
      - docker compose exec --env PORT=32897 nuxt-app yarn preview
  bash:
    cmds:
      - docker compose exec nuxt-app /bin/bash
