version: '3'

tasks:
  start:
    cmds:
      - docker compose up
  generate:
    cmds:
      - docker compose exec nuxt-app yarn generate
  bash:
    cmds:
      - docker compose exec nuxt-app /bin/bash
