# https://github.com/actions/deploy-pages#usage
name: Build static site using Nuxt then deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nuxt-app
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache-dependency-path: ./nuxt-app/yarn.lock
      - run: npm install
      - run: yarn generate
      - run: cp -R ./share ./.output/public/share
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./nuxt-app/.output/public

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github_pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
